[build]
  publish = "build"
  functions = "netlify/functions"

# (Optional) always set proper cache headers on static JSON if you publish any
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Vary = "Origin"
