// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
module.exports = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // <-- Must match your `intro.md` filename (without .md)
      label: 'Introduction',
      customProps: { hideStars: true },
    },
// sidebars.js
{
  type: 'category',
  label: 'Project Kickstarters',
  items: [
    {
      type: 'doc',
      id: 'project-kickstarters/python-project-bootstrap',
      label: 'Python Project Bootstrap',
      customProps: { hideStars: true },
    },
    {
      type: 'doc',
      id: 'project-kickstarters/git',
      label: 'Git',
      customProps: { hideStars: true },
    },
  ],
},

  // sidebars.js
module.exports = {
      type: 'category',
      label: 'Finance Courses',
      items: ['finance/monte-carlo', 'finance/Actions-indices', 'finance/fx', 'finance/skew-smile', 'finance/autocallables', 'finance/calls-and-puts', 
        'finance/forwards-dividends', 'finance/convexity-adjustment', 'finance/discountcurve'],
    },
    {
      type: 'category',
      label: 'Premium Courses',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'finance/volatility-handbook', // <— keep the same doc
          label: 'Volatility Handbook',
          customProps: { premium: true, badge: 'Premium' }, // keeps your gold badge
        },
      ],
    },
  ],
};

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
