// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
module.exports = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // <-- Must match your `intro.md` filename (without .md)
      label: 'Introduction',
    },
    {
    type: 'category',
    label: 'Project Kickstarters',
    items: ['project-kickstarters/python-project-bootstrap'],
  },
    {
      type: 'category',
      label: 'Git',
      items: ['git/git'],
    },
    {
      type: 'category',
      label: 'Finance',
      items: ['finance/test', 'finance/fx', 'finance/Actions-indices', 'finance/skew-smile', 'finance/autocallables', 'finance/calls-and-puts', 
        'finance/forwards-dividends', 'finance/convexity-adjustment', 'finance/discountcurve', 'finance/volatility-handbook'],
    },
  ],
};

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
